#################################################################
#                                                               #
#                       Packages/Fitness                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:

####################################################
#                                                  #
#               Sensors - Google Fit               #
#                                                  #
####################################################

  - platform: google_fit
    client_id: !secret google_fit_client_id
    client_secret: !secret google_fit_client_secret
    
####################################################
#                                                  #
#                  Sensors - MQTT                  #
#                                                  #
####################################################

  - platform: mqtt
    name: "James Steps"
    state_topic: "steps/james/huawei"
    
  - platform: mqtt
    name: "Tina Steps"
    state_topic: "steps/tina/samsung"

 