# dwains_theme

#################################################################
#                                                               #
#                  Addons/Garden/Star Jasmine                   #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                        Plant Type Image                       #
#                                                               #
#################################################################

- type: picture
  image: "https://live.staticflickr.com/5067/5689570518_48aae763ec_b.jpg"
  style: |
    ha-card {
      height: 125px;
      border-radius: 2.5px;
    }

#################################################################
#                                                               #
#                    Mi Flora Sensor Details                    #
#                                                               #
#################################################################

- type: custom:stack-in-card
  cards:
    - type: horizontal-stack
      cards:
        - type: markdown
          content: >
            <img width="125" src="https://apps-cdn.athom.com/app/com.mi.flora/1/00700bec-b736-440b-9dc4-fd1b5ab8336a/drivers/flora/assets/images/large.png"/><br>
        - type: vertical-stack
          cards:
            - type: markdown
              content: >
                <br>
                **Mi Flora**<br>
                {{ (data | fromjson)['firmware'] }}<br>
                {{ (data | fromjson)['last_update'] }}

####################################################
#                                                  #
#                Mi Flora - Battery                #
#                                                  #
####################################################

            - type: custom:bar-card
              name: ' '
              positions:
                value: 'outside'
              unit_of_measurement: '%'
              width: 125%
              entities:
                - entity: sensor.star_jasmine_battery
                  icon: mdi:battery
              severity:
                - color: rgb(163,0,0)
                  from: 0
                  to: 15
                - color: rgb(51,191,99)
                  from: 16
                  to: 100
              style: |
                ha-card {
                  --paper-item-icon-color: rgb(47,186,229);
                  border-radius: 5px;
                  height: 40px;
                }
                ha-icon	 {
                  margin-right: auto;
                  margin-left: auto;
                  margin-bottom: auto;
                  margin-top: -17px;
                }
                bar-card-indicator	 {
                  margin-right: auto;
                  margin-left: auto;
                  margin-bottom: auto;
                  margin-top: -17px;
                }
                bar-card-background	 {
                  margin-right: auto;
                  margin-left: auto;
                  margin-bottom: auto;
                  margin-top: -12.5px;
                  padding-right: 5px;
                  height: 15px;
                }
                bar-card-value	 {
                  margin-right: auto;
                  margin-left: auto;
                  margin-bottom: auto;
                  margin-top: -15px;
                  padding-left: 5px;
                }
  style: |
    ha-card {
      color: teal;
      border-radius: 2.5px;
    }

#################################################################
#                                                               #
#                       Mi Flora Sensors                        #
#                                                               #
#################################################################

- type: horizontal-stack
  cards:

####################################################
#                                                  #
#               Mi Flora - Moisture                #
#                                                  #
####################################################

    - type: custom:bar-card
      name: ' '
      icon: mdi:water
      positions:
        value: 'outside'
      target: 60
      unit_of_measurement: '%'
      width: 150%
      entity: sensor.star_jasmine_moisture
      severity:
        - color: rgb(163,0,0)
          from: 0
          to: 15
        - color: rgb(51,191,99)
          from: 16
          to: 60
        - color: rgb(163,0,0)
          from: 61
          to: 100
      style: |
        ha-card {
          --paper-item-icon-color: rgb(47,186,229);
          border-radius: 2.5px;
          height: 40px;
        }
        ha-icon	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
        }
        bar-card-indicator	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -17px;
        }
        bar-card-background	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -12.5px;
          padding-right: 5px;
          height: 15px;
        }
        bar-card-value	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
          padding-left: 5px;
        }

####################################################
#                                                  #
#             Mi Flora - Conductivity              #
#                                                  #
####################################################

    - type: custom:bar-card
      name: ' '
      icon: mdi:emoticon-poop
      positions:
        value: 'outside'
      target: 1500
      max: 2000
      unit_of_measurement: 'µS'
      width: 140%
      entity: sensor.star_jasmine_conductivity
      severity:
        - color: rgb(163,0,0)
          from: 0
          to: 200
        - color: rgb(51,191,99)
          from: 201
          to: 1500
        - color: rgb(163,0,0)
          from: 1501
          to: 2000
      style: |
        ha-card {
          --paper-item-icon-color: rgb(47,186,229);
          border-radius: 2.5px;
          height: 40px;
        }
        ha-icon	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
        }
        bar-card-indicator	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -17px;
        }
        bar-card-background	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -12.5px;
          padding-right: 5px;
          height: 15px;
        }
        bar-card-value	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
          padding-left: 5px;
        }

- type: horizontal-stack
  cards:

####################################################
#                                                  #
#             Mi Flora - Temperature               #
#                                                  #
####################################################

    - type: custom:bar-card
      name: ' '
      icon: mdi:thermometer
      positions:
        value: 'outside'
      target: 35
      max: 50
      unit_of_measurement: '°C'
      width: 150%
      entity: sensor.star_jasmine_temperature
      severity:
        - color: rgb(163,0,0)
          from: 0
          to: 10
        - color: rgb(51,191,99)
          from: 11
          to: 35
        - color: rgb(163,0,0)
          from: 36
          to: 50
      style: |
        ha-card {
          --paper-item-icon-color: rgb(47,186,229);
          border-radius: 2.5px;
          height: 40px;
        }
        ha-icon	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
        }
        bar-card-indicator	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -17px;
        }
        bar-card-background	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -12.5px;
          padding-right: 5px;
          height: 15px;
        }
        bar-card-value	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
          padding-left: 5px;
        }

####################################################
#                                                  #
#                 Mi Flora - Light                 #
#                                                  #
####################################################

    - type: custom:bar-card
      name: ' '
      positions:
        value: 'outside'
      target: 50000
      max: 60000
      unit_of_measurement: 'Lx'
      width: 150%
      entities:
        - entity: sensor.star_jasmine_light
          icon: mdi:weather-sunny
          severity:
            - color: rgb(163,0,0)
              from: 0
              to: 2000
            - color: rgb(51,191,99)
              from: 2000
              to: 50000
            - color: rgb(163,0,0)
              from: 50001
              to: 100000
      style: |
        ha-card {
          --paper-item-icon-color: rgb(47,186,229);
          border-radius: 2.5px;
          height: 40px;
        }
        ha-icon	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
        }
        bar-card-indicator	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -17px;
        }
        bar-card-background	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -12.5px;
          padding-right: 5px;
          height: 15px;
        }
        bar-card-value	 {
          margin-right: auto;
          margin-left: auto;
          margin-bottom: auto;
          margin-top: -15px;
          padding-left: 5px;
        }