####################################################
#                                                  #
#                      Alexa                       #
#                                                  #
####################################################

  - platform: alexa
    email: !secret alexa_user
    password: !secret alexa_pass
    url: amazon.com

####################################################
#                                                  #
#                      Kodi                        #
#                                                  #
####################################################

- platform: kodi
  host: ip
  name: Media 4K Kodi
  
- platform: kodi
  host: ip
  name: Bedroom Kodi
  
- platform: kodi
  host: ip
  name: Patio Kodi
  
- platform: kodi
  host: ip
  name: TTS Kodi
  username: kodi
  password: kodi
  
####################################################
#                                                  #
#                    Samsung TV                    #
#                                                  #
####################################################

- platform: samsungtv
  host: ip
  port: 8001
  name: Media 4K TV
  mac: mac
  
- platform: samsungtv
  host: ip
  name: mac
