####################################################
#                                                  #
#                    Time/Date                     #
#                                                  #
####################################################

  - platform: time_date
    display_options:
      - time
      - date
      - date_time
      - time_date
      - time_utc
      - beat
      
  - platform: worldclock
    time_zone: Australia/Sydney
    name: Claire Time
  
  - platform: worldclock
    time_zone: Europe/London
    name: Mum Time
    
####################################################
#                                                  #
#                   XiaoMi Raw                     #
#                                                  #
####################################################

  - platform: xiaomi_miio_raw
    name: Any Xiaomi MiIO device
    host: ip
    token: token