###################################################
#                                                 #
#     Home Assistant Main Configuration File      #
#                                                 #
###################################################

homeassistant:
  name: !secret name
  temperature_unit: C
  time_zone: !secret timezone
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: metric
  elevation: 6
  customize: !include includes/customize.yaml
  packages: !include_dir_named packages
  
###################################################
#                                                 #
#                     Panel                       #
#                                                 #
################################################### 

panel_iframe:
  configurator:
    title: Configurator
    icon: mdi:wrench
    url: configurator url
  nodered:
    title: Node-Red
    icon: mdi:shuffle-variant
    url: node red url
  sonweb:
    title: SonWEB
    icon: mdi:lightbulb-on
    url:  sonweb url

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################

config:

hassio:
api:
  api_password: !secret api_password
  
http:
  api_password: !secret http_password
  trusted_networks:
    - x.x.x.x

  cors_allowed_origins:
    - http://x.x.x.x
    - http://x.x.x.x:xxxxx

updater:
discovery:
conversation:
history:
logbook:
map:

####################################################
#                                                  #
#                 Customizations                   #
#                                                  #
####################################################

#customizer:
#  custom_ui: local
  
frontend:
  javascript_version: latest
  extra_html_url:
    - /local/custom_ui/fontawesome/hass-fontawesome-solid.html
    - /local/custom_ui/fontawesome/hass-fontawesome-regular.html
    - /local/custom_ui/fontawesome/hass-fontawesome-brands.html

custom_updater: 

####################################################
#                                                  #
#                      Logger                      #
#                                                  #
####################################################

logger:
  #default: warn
  #logs:
  #  custom_components.fan.xiaomi_miio_fan: debug
  #  miio: debug
    
####################################################
#                                                  #
#                     Recorder                     #
#                                                  #
####################################################

recorder:
  purge_interval: 2
  purge_keep_days: 5

####################################################
#                                                  #
#                      Cloud                       #
#                                                  #
####################################################

cloud:
  alexa:
    filter:
      include_entities:
        - group.all_lights
        - group.downstairs_lights
        - group.outside_lights
      include_domains:
        - switch
        - cover
        - input_boolean

####################################################
#                                                  #
#                      MQTT                        #
#                                                  #
####################################################

mqtt: 
  broker: myip
  port: myport
  username: !secret mqttuser
  password: !secret mqttpass
  
mqtt_statestream:
  base_topic: ha-main
  publish_attributes: true
  publish_timestamps: true
  
####################################################
#                                                  #
#                    Includes                      #
#                                                  #
####################################################

automation: !include includes/automations.yaml
camera: !include includes/cameras.yaml
fan: !include includes/fans.yaml
group: !include includes/groups.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
light: !include includes/lights.yaml
media_player: !include includes/media_players.yaml
notify: !include includes/notify.yaml
python_script: !include_dir_named python_scripts
scene: !include includes/scenes.yaml
script: !include includes/scripts.yaml
sensor: !include includes/sensors.yaml
switch: !include includes/switches.yaml
vacuum: !include includes/vacuums.yaml
xiaomi_aqara: !include includes/xiaomi.yaml
zone: !include includes/zones.yaml
