#################################################################
#                                                               #
#                      Packages/Lighting                        #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
## Light Switches
    switch.front_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Front Light"
    switch.lounge_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Lounge Light"
    switch.hall_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Hall Light"
    switch.kitchen_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Kitchen Light"
    switch.dining_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Dining Light"
    switch.patio_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Patio Light"
    switch.master_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Master Light"
    switch.jackson_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Jackson Light"
    switch.hudson_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Hudson Light"
    switch.bathroom_light_switch:
      icon: 'mdi:lightbulb'
      friendly_name: "Bathroom Light"
    switch.bathroom_fan_switch:
      icon: 'mdi:fan'
      friendly_name: "Bathroom Fan"
    switch.bathroom_heat_switch:
      icon: 'mdi:fire'
      friendly_name: "Bathroom Heat"
    switch.fairy_light_power:
      icon: mdi:lightbulb
      friendly_name: Fairy Lighting
      assumed_state: false
    switch.fairy_light_mode_4:
      icon: mdi:lightbulb-on-outline
      friendly_name: Fairy Flash Mode
      assumed_state: false
    light.gateway_light_7811dcfd812f:
      friendly_name: TV Back Light
    light.gateway_light_7811dce13ad6:
      friendly_name: PC Back Light
    switch.plug_158d0001f24e2b:
      friendly_name: Entertainment Lighting
      
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  downstairs lights:
    name: Downstairs Lights
    view: no
    entities:
      - switch.lounge_light_switch
      - light.lounge_bulb
      - switch.kitchen_light_switch
      - switch.dining_light_switch
      - light.dining_bulb
      
  outside lights:
    name: Outside Lights
    view: no
    entities:
      - switch.patio_light_switch
      - light.entrance_bulb
      
  master bedroom lights:
    name: Master Bedroom Lights
    view: no
    entities:
      - switch.master_light_switch
      - light.bedroom_bulb
      - switch.bedroom_wardrobe_switch
      
  bathroom switches:
    name: Bathroom Switches
    view: no
    entities:
      - switch.bathroom_light_switch
      - switch.bathroom_fan_switch
      - switch.bathroom_heat_switch
      
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:
## This turns the Media TV backlight on
  - alias: 'TV Back Light On'
    trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    action:
    - service: script.turn_on
      data:
        entity_id: script.blue_tv_light
        
## This turns the Media TV backlight off
  - alias: 'TV Back Light Off'
    trigger:
    - platform: time
      at: '22:00'
    action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dcfd812f
        
## This turns the PC backlight on
  - alias: 'PC Back Light On'
    trigger:
    - platform: state
      entity_id: sun.sun
      to: 'below_horizon'
    action:
    - service: script.turn_on
      data:
        entity_id: script.blue_pc_light
        
## This turns the PC backlight off
  - alias: 'PC Back Light Off'
    trigger:
    - platform: time
      at: '22:00'
    action:
    - service: light.turn_off
      data:
        entity_id: light.gateway_light_7811dce13ad6

## This turns on the patio light upon motion for 2 mins after sun is below horizon        
  - alias: 'Patio Motion Light'
    trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d000200ea5b
      to: 'on'
    condition:
    - condition: state
      state: below_horizon
      entity_id: sun.sun
    action:
    - service: switch.turn_on
      data:
        entity_id: switch.patio_light_switch
    - delay: 00:02:00
    - service: switch.turn_off
      data:
        entity_id: switch.patio_light_switch
        
## This turns on the entrance light upon motion for 2 mins after sun is below horizon        
  - alias: 'Entry Motion Light'
    trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0001e5d147
      to: 'on'
    condition:
    - condition: state
      state: below_horizon
      entity_id: sun.sun
    action:
    - service: light.turn_on
      data:
        entity_id: light.entrance_bulb
    - delay: 00:02:00
    - service: light.turn_off
      data:
        entity_id: light.entrance_bulb
        
## This turns on the hall light at 5pm       
  - alias: 'Hall Light On'
    trigger:
    - platform: time
      at: '17:00'
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.hall_dusk
        
## This dims the hall light at 6:30pm       
  - alias: 'Hall Light Dim'
    trigger:
    - platform: time
      at: '18:30'
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.hall_dim
        
## This turns the hall light back up at 6:00am       
  - alias: 'Hall Light Normal'
    trigger:
    - platform: time
      at: '06:00'
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.hall_normal
        
## This turns the hall light off at 8:00am       
  - alias: 'Hall Light Off'
    trigger:
    - platform: time
      at: '08:00'
    action:
    - service: light.turn_off
      data:
        entity_id: light.hall_bulb
        
## This turns on the fairy lights after sun is below horizon        
  - alias: 'Fairy Lights On'
    trigger:
    - platform: sun
      event: sunset
      offset: "-00:30:00"
    action:
    - service: script.1523649643350
    
## This turns off the fairy lights at 10pm       
  - alias: 'Fairy Lights Off'
    trigger:
    - platform: time
      at: '22:00'
    action:
    - service: switch.turn_off
      data:
        entity_id: switch.fairy_light_power
