#################################################################
#                                                               #
#                   Packages/Things Status                      #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:

  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  cameras:
    name: Cameras
    view: no
    entities:
      - binary_sensor.baby_monitor_camera
      - binary_sensor.dining_camera
      - binary_sensor.lounge_camera
      - binary_sensor.bedroom_camera
      #- binary_sensor.jackson_camera
      #- binary_sensor.hudson_camera
      #- binary_sensor.staircase_camera
      
  ir blasters:
    name: IR Blasters
    view: no
    entities:
      - binary_sensor.ir_blaster_downstairs
      - binary_sensor.ir_blaster_upstairs
      - binary_sensor.ir_blaster_patio
      
  sonoff switches:
    name: Sonoff Swiches
    view: no
    entities:
      - binary_sensor.lounge_fan_switch
      - binary_sensor.dining_light_switch
      - binary_sensor.kitchen_light_switch
      - binary_sensor.patio_light_switch
      - binary_sensor.lounge_light_switch
      - binary_sensor.master_bedroom_fan_switch
      
  lamps:
    name: Lamps
    view: no
    entities:
      - binary_sensor.hall_light_bulb
      - binary_sensor.lounge_light_bulb
      - binary_sensor.dining_light_bulb
      - binary_sensor.entry_light_bulb
      - binary_sensor.bedroom_light_bulb
      
  ble_trackers:
    name: BLE Trackers
    view: no
    entities:
      - binary_sensor.ble_tracker_downstairs
      - binary_sensor.ble_tracker_upstairs
      
  esp_sensors:
    name: ESP Sensors
    view: no
    entities:
      - binary_sensor.garage_door
      - binary_sensor.coffee_machine

#################################################################
#                                                               #
#                       Device Tracker                          #
#                                                               #
#################################################################

device_tracker:
  - platform: ping
    hosts:
      baby_monitor_camera: 10.0.10.1
      dining_camera: 10.0.10.2
      living_camera: 10.0.10.3
      bedroom_camera: 10.0.10.4
      jackson_camera: 10.0.10.5
      hudson_camera: 10.0.10.6
      staircase_camera: 10.0.10.7
      ir_blaster_downstairs: 10.0.30.1
      ir_blaster_patio: 10.0.30.2
      ir_blaster_upstairs: 10.0.30.3
      hall_light_bulb: 10.0.50.1
      lounge_light_bulb: 10.0.50.2
      entry_light_bulb: 10.0.50.3
      dining_light_bulb: 10.0.50.4
      bedroom_light_bulb: 10.0.50.5
      lounge_fan_switch: 10.0.60.1
      kitchen_light_switch: 10.0.60.2
      patio_light_switch: 10.0.60.3
      lounge_light_switch: 10.0.60.4
      master_bedroom_fan_switch: 10.0.60.5
      dining_light_switch: 10.0.60.6
      patio_led_switch: 10.0.70.1
      garage_door_sensor: 10.0.80.1
      coffee_machine_sensor: 10.0.80.2
      ble_tracker_downstairs: 10.0.20.6
      ble_tracker_upstairs: 10.0.20.7
      playroom_fan: 10.0.100.1
      robovac: 10.0.100.2
      
#################################################################
#                                                               #
#                       Binary Sensors                          #
#                                                               #
#################################################################

binary_sensor:
  - platform: template
    sensors:
## Cameras
      baby_monitor_camera:
        friendly_name: Baby Monitor
        device_class: connectivity
        entity_id: device_tracker.baby_monitor_camera
        value_template: "{{ is_state('device_tracker.baby_monitor_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.baby_monitor_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}
      dining_camera:
        friendly_name: Dining Camera
        device_class: connectivity
        entity_id: device_tracker.dining_camera
        value_template: "{{ is_state('device_tracker.dining_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.dining_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}
      lounge_camera:
        friendly_name: Lounge Camera
        device_class: connectivity
        entity_id: device_tracker.living_camera
        value_template: "{{ is_state('device_tracker.living_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.living_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}
      bedroom_camera:
        friendly_name: Bedroom Camera
        device_class: connectivity
        entity_id: device_tracker.bedroom_camera
        value_template: "{{ is_state('device_tracker.bedroom_camera', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.bedroom_camera', 'home') %}
            mdi:cctv
          {% else %}
            mdi:alert
          {% endif %}
      #jackson_camera:
      #  friendly_name: Jackson Camera
      #  device_class: connectivity
      #  entity_id: device_tracker.jackson_camera
      #  value_template: "{{ is_state('device_tracker.jackson_camera', 'home') }}"
      #  icon_template: >-
      #    {% if is_state('device_tracker.jackson_camera', 'home') %}
      #      mdi:cctv
      #    {% else %}
      #      mdi:alert
      #    {% endif %} 
      #hudson_camera:
      #  friendly_name: Hudson Camera
      #  device_class: connectivity
      #  entity_id: device_tracker.hudson_camera
      #  value_template: "{{ is_state('device_tracker.hudson_camera', 'home') }}"
      #  icon_template: >-
      #    {% if is_state('device_tracker.hudson_camera', 'home') %}
      #      mdi:cctv
      #    {% else %}
      #      mdi:alert
      #    {% endif %}  
      #staircase_camera:
      #  friendly_name: Staircase Camera
      #  device_class: connectivity
      #  entity_id: device_tracker.staircase_camera
      #  value_template: "{{ is_state('device_tracker.staircase_camera', 'home') }}"
      #  icon_template: >-
      #    {% if is_state('device_tracker.staircase_camera', 'home') %}
      #      mdi:cctv
      #    {% else %}
      #      mdi:alert
      #    {% endif %}          
    
## IR Blasters
      ir_blaster_downstairs:
        friendly_name: IR Blaster Downstairs
        device_class: connectivity
        entity_id: device_tracker.ir_blaster_downstairs
        value_template: "{{ is_state('device_tracker.ir_blaster_downstairs', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.ir_blaster_downstairs', 'home') %}
            mdi:remote
          {% else %}
            mdi:alert
          {% endif %}
      ir_blaster_upstairs:
        friendly_name: IR Blaster Upstairs
        device_class: connectivity
        entity_id: device_tracker.ir_blaster_upstairs
        value_template: "{{ is_state('device_tracker.ir_blaster_upstairs', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.ir_blaster_upstairs', 'home') %}
            mdi:remote
          {% else %}
            mdi:alert
          {% endif %}
      ir_blaster_patio:
        friendly_name: IR Blaster Patio
        device_class: connectivity
        entity_id: device_tracker.ir_blaster_patio
        value_template: "{{ is_state('device_tracker.ir_blaster_patio', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.ir_blaster_patio', 'home') %}
            mdi:remote
          {% else %}
            mdi:alert
          {% endif %}
## Sonoff Swiches
      lounge_fan_switch:
        friendly_name: Lounge Fan Switch
        device_class: connectivity
        entity_id: device_tracker.lounge_fan_switch
        value_template: "{{ is_state('device_tracker.lounge_fan_switch', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.lounge_fan_switch', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
      kitchen_light_switch:
        friendly_name: Kitchen Light Switch
        device_class: connectivity
        entity_id: device_tracker.kitchen_light_switch
        value_template: "{{ is_state('device_tracker.kitchen_light_switch', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.kitchen_light_switch', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
      kitchen_dining_light_switch:
        friendly_name: Dining Light Switch
        device_class: connectivity
        entity_id: device_tracker.dining_light_switch
        value_template: "{{ is_state('device_tracker.dining_light_switch', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.dining_light_switch', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
      patio_light_switch:
        friendly_name: Patio Light Switch
        device_class: connectivity
        entity_id: device_tracker.patio_light_switch
        value_template: "{{ is_state('device_tracker.patio_light_switch', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.patio_light_switch', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
      lounge_light_switch:
        friendly_name: Lounge Light Switch
        device_class: connectivity
        entity_id: device_tracker.lounge_light_switch
        value_template: "{{ is_state('device_tracker.lounge_light_switch', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.lounge_light_switch', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
      master_bedroom_fan_switch:
        friendly_name: Bedroom Fan Switch
        device_class: connectivity
        entity_id: device_tracker.master_bedroom_fan_switch
        value_template: "{{ is_state('device_tracker.master_bedroom_fan_switch', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.master_bedroom_fan_switch', 'home') %}
            mdi:toggle-switch
          {% else %}
            mdi:alert
          {% endif %}
## Light Bulbs
      hall_light_bulb:
        friendly_name: Hall Light Bulb
        device_class: connectivity
        entity_id: device_tracker.hall_light_bulb
        value_template: "{{ is_state('device_tracker.hall_light_bulb', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.hall_light_bulb', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}
      entry_light_bulb:
        friendly_name: Entry Light Bulb
        device_class: connectivity
        entity_id: device_tracker.entry_light_bulb
        value_template: "{{ is_state('device_tracker.entry_light_bulb', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.entry_light_bulb', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}
      lounge_light_bulb:
        friendly_name: Lounge Light Bulb
        device_class: connectivity
        entity_id: device_tracker.kitchen_light_bulb
        value_template: "{{ is_state('device_tracker.lounge_light_bulb', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.lounge_light_bulb', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}
      dining_light_bulb:
        friendly_name: Dining Light Bulb
        device_class: connectivity
        entity_id: device_tracker.dining_light_bulb
        value_template: "{{ is_state('device_tracker.dining_light_bulb', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.dining_light_bulb', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}
      bedroom_light_bulb:
        friendly_name: Bedroom Light Bulb
        device_class: connectivity
        entity_id: device_tracker.bedroom_light_bulb
        value_template: "{{ is_state('device_tracker.bedroom_light_bulb', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.bedroom_light_bulb', 'home') %}
            mdi:lightbulb
          {% else %}
            mdi:alert
          {% endif %}
## BLE Trackers
      ble_tracker_downstairs:
        friendly_name: BLE Tracker Downstairs
        device_class: connectivity
        entity_id: device_tracker.ble_tracker_downstairs
        value_template: "{{ is_state('device_tracker.ble_tracker_downstairs', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.ble_tracker_downstairs', 'home') %}
            mdi:bluetooth
          {% else %}
            mdi:alert
          {% endif %}
      ble_tracker_upstairs:
        friendly_name: BLE Tracker Upstairs
        device_class: connectivity
        entity_id: device_tracker.ble_tracker_upstairs
        value_template: "{{ is_state('device_tracker.ble_tracker_upstairs', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.ble_tracker_upstairs', 'home') %}
            mdi:bluetooth
          {% else %}
            mdi:alert
          {% endif %}
## ESP Sensors
      garage_door:
        friendly_name: Garage Door Sensor
        device_class: connectivity
        entity_id: device_tracker.garage_door_sensor
        value_template: "{{ is_state('device_tracker.garage_door_sensor', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.garage_door_sensor', 'home') %}
            mdi:garage
          {% else %}
            mdi:alert
          {% endif %}
      coffee_machine:
        friendly_name: Coffee Machine Sensor
        device_class: connectivity
        entity_id: device_tracker.coffee_machine_sensor
        value_template: "{{ is_state('device_tracker.coffee_machine_sensor', 'home') }}"
        icon_template: >-
          {% if is_state('device_tracker.coffee_machine_sensor', 'home') %}
            mdi:coffee
          {% else %}
            mdi:alert
          {% endif %}
      
