#################################################################
#                                                               #
#                   Packages/Climate Control                    #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
## Downstairs Climate Control
    sensor.temperature_158d0001f558f5:
      friendly_name: Downstairs Temperature
    sensor.humidity_158d0001f558f5:
      friendly_name: Downstairs Humidity 
    sensor.illumination_158d0001e5d118:
      friendly_name: Downstairs LUX
    input_select.lounge_aircon:
      icon: mdi:snowflake
    input_select.lounge_fan:
      icon: mdi:fan 
    binary_sensor.switch_158d000201ce4e:
      friendly_name: Lounge Fan Switch  
    climate.downstairs_climate:
      icon: mdi:snowflake
    climate.upstairs_climate:
      icon: mdi:snowflake
      
## Upstairs Climate Control
    sensor.temperature_158d0001f53de9:
      friendly_name: Bedroom Temperature
    sensor.humidity_158d0001f53de9:
      friendly_name: Bedroom Humidity 
    sensor.illumination_158d0001e63803:
      friendly_name: Bedroom LUX
    input_select.master_bedroom_aircon:
      icon: mdi:snowflake
    input_select.bedroom_fan:
      icon: mdi:fan 
    binary_sensor.switch_158d000233a19d:
      friendly_name: Bedside Fan Switch
    binary_sensor.switch_158d000215aa27:
      friendly_name: Bedroom Wall Fan Switch
      
## Playroom Climate Control
    sensor.temperature_158d0001f56682:
      friendly_name: Playroom Temperature
    sensor.humidity_158d0001f56682:
      friendly_name: Playroom Humidity  
    sensor.illumination_158d0001e5cf11:
      friendly_name: Playroom LUX
      
    sensor.lower_temperature:
      friendly_name: Downstairs Temperature
      icon: mdi:sofa
    sensor.upstairs_temperature:
      icon: mdi:hotel
      
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
## Downstairs Climate Control
  climate control:
    name: Climate Control
    view: no
    entities:
      - sensor.temperature_158d0001f558f5
      - sensor.humidity_158d0001f558f5
      - sensor.illumination_158d0001e5d118
      - input_select.lounge_aircon
      - input_select.lounge_fan
      - climate.downstairs_climate
      
## Upstairs Climate Control
  master bedroom climate:
    name: Master Bedroom Climate
    view: no
    entities:
      - sensor.temperature_158d0001f53de9
      - sensor.humidity_158d0001f53de9
      - sensor.illumination_158d0001e63803
      - input_select.master_bedroom_aircon
      - input_select.bedroom_fan
      - climate.upstairs_climate
      
## Playroom Climate Control
  play room climate:
    name: Play Room Climate
    view: no
    entities:
      - sensor.temperature_158d0001f56682
      - sensor.humidity_158d0001f56682
      - sensor.illumination_158d0001e5cf11
      - fan.xiaomi_smart_fan
      #- input_select.playroom_fan
      
#################################################################
#                                                               #
#                        User Inputs                            #
#                                                               #
#################################################################

input_select:
## Downstairs Air Conditioner
  lounge_aircon:
    name: Lounge Climate
    options:
      - Climate Off
      - Cool
      - Heat
    initial: Climate Off
    #icon: mdi:snowflake
    
## Lounge Fan  
  lounge_fan:
    name: Lounge Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial: Fan Off
    #icon: mdi:fan
    
## Master Bedroom Air Conditioner
  master_bedroom_aircon:
    name: Master Bedroom Climate
    options:
      - Climate Off
      - Cool
      - Heat
    initial: Climate Off
    #icon: mdi:snowflake

## Master Bedroom Fan    
  bedroom_fan:
    name: Bedroom Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial:  Fan Off
    #icon: mdi:fan 
    
## Playroom

#################################################################
#                                                               #
#                             Fans                              #
#                                                               #
#################################################################

#fan:
## Playroom Fan
#  - platform: xiaomi_miio_fan
#    name: Xiaomi Smart Fan
#    host: 10.0.100.1
#    token: 2f4d188389e9425a7cc2d77947413e24

#################################################################
#                                                               #
#                   Custom Broadlink Climate                    #
#                                                               #
#################################################################

climate:
  - platform: broadlink
    name: Downstairs Climate
    host: 10.0.30.1
    mac: '34:EA:34:88:DA:06'
    ircodes_ini: 'broadlink_climate_codes/gree.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temperature_158d0001f558f5
    default_operation: 'off'
    default_fan_mode: mid
    customize:
      operations:
        - 'off'
        - cool
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
        
  - platform: broadlink
    name: Upstairs Climate
    host: 10.0.30.3
    mac: '78:0F:77:00:75:4C'
    ircodes_ini: 'broadlink_climate_codes/panasonic.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temperature_158d0001f53de9
    default_operation: 'off'
    default_fan_mode: mid
    customize:
      operations:
        - 'off'
        - cool
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
    
#################################################################
#                                                               #
#                            Scenes                             #
#                                                               #
#################################################################

scene:
## Downstairs Air Conditioner
  - name: "Climate Cool"
    entities:
      switch.aircon_mode_cool: on

  - name: "Climate Heat"
    entities:
      switch.aircon_mode_heat: on

  - name: "Climate Off"
    entities:
      switch.aircon_power: off
      
## Upstairs Air Conditioner - This Section needs to be fixed before summer ir codes are incorrect
  - name: "Bedroom Climate Mode"
    entities:
      switch.bedroom_aircon_mode: on

  - name: "Bedroom Climate Off"
    entities:
      switch.bedroom_aircon_power: off

  - name: "Bedroom Climate On"
    entities:
      switch.bedroom_aircon_power: on
      
#################################################################
#                                                               #
#                           Sensors                             #
#                                                               #
#################################################################

sensor:
  - platform: min_max
    name: "Lower Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.temperature_158d0001f558f5
      - sensor.temperature_158d0001f56682
      
  - platform: min_max
    name: "Upstairs Temperature"
    type: mean
    round_digits: 1
    entity_ids:
      - sensor.temperature_158d0001f534e1
      - sensor.temperature_158d0001f53de9
      - sensor.temperature_158d0001f54df3
      - sensor.temperature_158d00022c7248
      
  - platform: mqtt
    name: "Lounge Fan Switch"
    state_topic: "lounge_fan"
    
  - platform: mqtt
    name: "Bedroom Fan Switch"
    state_topic: "bedroom_fan"
    
  - platform: mqtt
    name: "Jackson Fan Switch"
    state_topic: "jackson_fan"
    
  - platform: mqtt
    name: "Hudson Fan Switch"
    state_topic: "hudson_fan"
    
#################################################################
#                                                               #
#                             Fan                               #
#                                                               #
#################################################################

fan:

### Bedroom Fan ###
  - platform: mqtt  
    name: "Bedroom Fan"
    command_topic: "cmnd/bedroom_fan/FanSpeed"
    speed_command_topic: "cmnd/bedroom_fan/FanSpeed"    
    state_topic: "stat/bedroom_fan/RESULT"
    speed_state_topic: "stat/bedroom_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.bedroom_fan.state == 'off' -%}0{%- elif states.fan.bedroom_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/bedroom_fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high

### Lounge Fan ###
  - platform: mqtt  
    name: "Lounge Fan"
    command_topic: "cmnd/lounge_fan/FanSpeed"
    speed_command_topic: "cmnd/lounge_fan/FanSpeed"    
    state_topic: "stat/lounge_fan/RESULT"
    speed_state_topic: "stat/lounge_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.lounge_fan.state == 'off' -%}0{%- elif states.fan.lounge_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/lounge_fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high
      
### Jackson Fan ###
  - platform: mqtt  
    name: "Jackson Fan"
    command_topic: "cmnd/jackson_fan/FanSpeed"
    speed_command_topic: "cmnd/jackson_fan/FanSpeed"    
    state_topic: "stat/jackson_fan/RESULT"
    speed_state_topic: "stat/jackson_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.jackson_fan.state == 'off' -%}0{%- elif states.fan.jackson_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/jackson_fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high
      
### Hudson Fan ###
  - platform: mqtt  
    name: "Hudson Fan"
    command_topic: "cmnd/hudson_fan/FanSpeed"
    speed_command_topic: "cmnd/hudson_fan/FanSpeed"    
    state_topic: "stat/hudson_fan/RESULT"
    speed_state_topic: "stat/hudson_fan/RESULT"
    state_value_template: >
      {% if value_json.FanSpeed is defined %}
        {% if value_json.FanSpeed == 0 -%}0{%- elif value_json.FanSpeed > 0 -%}4{%- endif %}
      {% else %}
        {% if states.fan.hudson_fan.state == 'off' -%}0{%- elif states.fan.hudson_fan.state == 'on' -%}4{%- endif %}
      {% endif %}
    speed_value_template: "{{ value_json.FanSpeed }}"
    availability_topic: tele/hudson_fan/LWT
    payload_off: "0"
    payload_on: "4"
    payload_low_speed: "1"
    payload_medium_speed: "2"
    payload_high_speed: "3"
    payload_available: Online
    payload_not_available: Offline
    speeds:
      - off
      - low
      - medium
      - high
