#################################################################
#                                                               #
#                   Packages/Climate Control                    #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
## Downstairs Climate Control
    sensor.temperature_158d0001f558f5:
      friendly_name: Downstairs Temperature
    sensor.humidity_158d0001f558f5:
      friendly_name: Downstairs Humidity 
    sensor.illumination_158d0001e5d118:
      friendly_name: Downstairs LUX
    input_select.lounge_aircon:
      icon: mdi:snowflake
    input_select.lounge_fan:
      icon: mdi:fan 
    binary_sensor.switch_158d000201ce4e:
      friendly_name: Lounge Fan Switch  
    climate.downstairs_climate:
      icon: mdi:snowflake
    climate.upstairs_climate:
      icon: mdi:snowflake
      
## Upstairs Climate Control
    sensor.temperature_158d0001f53de9:
      friendly_name: Bedroom Temperature
    sensor.humidity_158d0001f53de9:
      friendly_name: Bedroom Humidity 
    sensor.illumination_158d0001e63803:
      friendly_name: Bedroom LUX
    input_select.master_bedroom_aircon:
      icon: mdi:snowflake
    input_select.bedroom_fan:
      icon: mdi:fan 
    binary_sensor.switch_158d000233a19d:
      friendly_name: Bedside Fan Switch
    binary_sensor.switch_158d000215aa27:
      friendly_name: Bedroom Wall Fan Switch
      
## Playroom Climate Control
    sensor.temperature_158d0001f56682:
      friendly_name: Playroom Temperature
    sensor.humidity_158d0001f56682:
      friendly_name: Playroom Humidity  
    sensor.illumination_158d0001e5cf11:
      friendly_name: Playroom LUX
      
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
## Downstairs Climate Control
  climate control:
    name: Climate Control
    view: no
    entities:
      - sensor.temperature_158d0001f558f5
      - sensor.humidity_158d0001f558f5
      - sensor.illumination_158d0001e5d118
      - input_select.lounge_aircon
      - input_select.lounge_fan
      - climate.downstairs_climate
      
## Upstairs Climate Control
  master bedroom climate:
    name: Master Bedroom Climate
    view: no
    entities:
      - sensor.temperature_158d0001f53de9
      - sensor.humidity_158d0001f53de9
      - sensor.illumination_158d0001e63803
      - input_select.master_bedroom_aircon
      - input_select.bedroom_fan
      - climate.upstairs_climate
      
## Playroom Climate Control
  play room climate:
    name: Play Room Climate
    view: no
    entities:
      - sensor.temperature_158d0001f56682
      - sensor.humidity_158d0001f56682
      - sensor.illumination_158d0001e5cf11
      - fan.xiaomi_smart_fan
      #- input_select.playroom_fan
      
#################################################################
#                                                               #
#                        User Inputs                            #
#                                                               #
#################################################################

input_select:
## Downstairs Air Conditioner
  lounge_aircon:
    name: Lounge Climate
    options:
      - Climate Off
      - Cool
      - Heat
    initial: Climate Off
    #icon: mdi:snowflake
    
## Lounge Fan  
  lounge_fan:
    name: Lounge Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial: Fan Off
    #icon: mdi:fan
    
## Master Bedroom Air Conditioner
  master_bedroom_aircon:
    name: Master Bedroom Climate
    options:
      - Climate Off
      - Cool
      - Heat
    initial: Climate Off
    #icon: mdi:snowflake

## Master Bedroom Fan    
  bedroom_fan:
    name: Bedroom Fan 
    options:
      - Fan Off
      - Low 
      - Medium
      - High
    initial:  Fan Off
    #icon: mdi:fan 
    
## Playroom

#################################################################
#                                                               #
#                             Fans                              #
#                                                               #
#################################################################

#fan:
## Playroom Fan
#  - platform: xiaomi_miio_fan
#    name: Xiaomi Smart Fan
#    host: 10.0.100.1
#    token: 2f4d188389e9425a7cc2d77947413e24

#################################################################
#                                                               #
#                   Custom Broadlink Climate                    #
#                                                               #
#################################################################

climate:
  - platform: broadlink
    name: Downstairs Climate
    host: 10.0.30.1
    mac: '34:EA:34:88:DA:06'
    ircodes_ini: 'broadlink_climate_codes/gree.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temperature_158d0001f558f5
    default_operation: 'off'
    default_fan_mode: mid
    customize:
      operations:
        - 'off'
        - cool
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
        
  - platform: broadlink
    name: Upstairs Climate
    host: 10.0.30.3
    mac: '78:0F:77:00:75:4C'
    ircodes_ini: 'broadlink_climate_codes/panasonic.ini'
    min_temp: 16
    max_temp: 30
    target_temp: 20
    target_temp_step: 1
    temp_sensor: sensor.temperature_158d0001f53de9
    default_operation: 'off'
    default_fan_mode: mid
    customize:
      operations:
        - 'off'
        - cool
        - heat
      fan_modes:
        - low
        - mid
        - high
        - auto
    
#################################################################
#                                                               #
#                            Scenes                             #
#                                                               #
#################################################################

scene:
## Downstairs Air Conditioner
  - name: "Climate Cool"
    entities:
      switch.aircon_mode_cool: on

  - name: "Climate Heat"
    entities:
      switch.aircon_mode_heat: on

  - name: "Climate Off"
    entities:
      switch.aircon_power: off
      
## Upstairs Air Conditioner - This Section needs to be fixed before summer ir codes are incorrect
  - name: "Bedroom Climate Mode"
    entities:
      switch.bedroom_aircon_mode: on

  - name: "Bedroom Climate Off"
    entities:
      switch.bedroom_aircon_power: off

  - name: "Bedroom Climate On"
    entities:
      switch.bedroom_aircon_power: on
      
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

## Input Select for Downstairs Climate Off
  - alias: Lounge Climate Off
    trigger:
    - platform: state
      entity_id: input_select.lounge_aircon
      to: Climate Off
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.climate_off
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Downstairs Climate Off"
        
## Input Select for Downstairs Climate Cool
  - alias: Lounge Climate Cool
    trigger:
    - platform: state
      entity_id: input_select.lounge_aircon
      to: Climate Cool
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.climate_cool
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Climate Control On lets cool this place down."
        
## Input Select for Downstairs Climate Heat
  - alias: Lounge Climate Heat
    trigger:
    - platform: state
      entity_id: input_select.lounge_aircon
      to: Climate Heat
    action:
    - service: scene.turn_on
      data:
        entity_id: scene.climate_heat
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Climate Control On lets warm this place up."

## Input Select for Fan Off
  - alias: Lounge Fan Off
    trigger:
    - platform: state
      entity_id: input_select.lounge_fan
      to: Fan Off
    action:
    - service: script.1521695181969
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Lounge Fan Off"
        
## Input Select for Fan Low 
  - alias: Lounge Fan Low
    trigger:
    - platform: state
      entity_id: input_select.lounge_fan
      to: Low
    action:
    - service: script.1521695117457
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Fan Speed Low"
        
## Input Select for Fan Medium 
  - alias: Lounge Fan Medium
    trigger:
    - platform: state
      entity_id: input_select.lounge_fan
      to: Medium
    action:
    - service: script.1521695035815
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Fan Speed Medium"
        
## Input Select for Fan High
  - alias: Lounge Fan High
    trigger:
    - platform: state
      entity_id: input_select.lounge_fan
      to: High
    action:
    - service: script.1521694972303
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Fan Speed High"
        
##Lounge Fan Wall Switch
  - alias: Lounge Wall Fan Switch
    trigger:
    - platform: event
      event_type: click
      event_data:
        click_type: single
        entity_id: binary_sensor.switch_158d000201ce4e
    action:
    - service: input_select.select_next
      data: 
        entity_id: input_select.lounge_fan
        

## Input Select for Bedroom Fan Off
  - alias: Bedroom Fan Off
    trigger:
    - platform: state
      entity_id: input_select.bedroom_fan
      to: Fan Off
    action:
    - service: script.1521695537041
    
## Input Select for Bedroom Fan Low
  - alias: Bedroom Fan Low
    trigger:
    - platform: state
      entity_id: input_select.bedroom_fan
      to: Low
    action:
    - service: script.1521695486416
    
## Input Select for Bedroom Fan Medium
  - alias: Bedroom Fan Medium
    trigger:
    - platform: state
      entity_id: input_select.bedroom_fan
      to: Medium
    action:
    - service: script.1521695283264
    
## Input Select for Bedroom Fan High
  - alias: Bedroom Fan Medium
    trigger:
    - platform: state
      entity_id: input_select.bedroom_fan
      to: High
    action:
    - service: script.1521695238080
    
##Bedside Fan Switch
  - alias: Bedside Fan Switch
    trigger:
    - platform: event
      event_type: click
      event_data:
        click_type: single
        entity_id: binary_sensor.switch_158d000233a19
    action:
    - service: input_select.select_next
      data: 
        entity_id: input_select.bedroom_fan
        
##Bedroom Fan Wall Switch
  - alias: Bedroom Fan Wall Switch
    trigger:
    - platform: event
      event_type: click
      event_data:
        click_type: single
        entity_id: binary_sensor.switch_158d000215aa27
    action:
    - service: input_select.select_next
      data: 
        entity_id: input_select.bedroom_fan
