#################################################################
#                                                               #
#                       Packages/Presence                       #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:
    sensor.commute_to_work:
      icon: 'mdi:car'
    sensor.commute_to_home:
      icon: 'mdi:home-variant'
 
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
################################################################# 
      
group:
  people:
    name: People
    view: no
    entities:
      - sensor.james
      - sensor.battery_james
      - sensor.tina
      - sensor.battery_tina
      - sensor.commute_to_work
      - sensor.commute_to_home
      
#################################################################
#                                                               #
#                      Device Trackers                          #
#                                                               #
################################################################# 

device_tracker:
  - platform: ping
    hosts:
      james_phone: 10.0.5.1
      tina_phone: 10.0.5.4
      
  - platform: owntracks
    max_gps_accuracy: 200
    
#################################################################
#                                                               #
#                        Input Boolean                          #
#                                                               #
#################################################################

input_boolean: 
  james_home:
    name: James
    initial: off
    icon: mdi:account
    
  tina_home:
    name: Tina
    initial: off
    icon: mdi:account
    
#################################################################
#                                                               #
#                          Sensors                              #
#                                                               #
################################################################# 

## Batteries
sensor:
  - platform: mqtt
    state_topic: "owntracks/admin/samsung"
    name: "Battery James"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    device_class: battery
    
  - platform: mqtt
    state_topic: "owntracks/admin/iphone"
    name: "Battery Tina"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
    device_class: battery

##Bluetooth Presence Detection    
  - platform: mqtt
    state_topic: 'location/owner/downstairs/A0:10:81:64:82:CB'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'James Downstairs'
    
  - platform: mqtt
    state_topic: 'location/owner/upstairs/A0:10:81:64:82:CB'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'James Upstairs'
    
  - platform: mqtt
    state_topic: 'location/owner/downstairs/48:3B:38:A6:60:1C'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Tina Downstairs'
    
  - platform: mqtt
    state_topic: 'location/owner/upstairs/48:3B:38:A6:60:1C'
    value_template: '{{ value_json.confidence }}'
    unit_of_measurement: '%'
    name: 'Tina Upstairs'

## Get mean average of BLE Presence Detection Sensors    
  - platform: min_max
    name: "James Home Occupancy Confidence"
    type: mean
    round_digits: 0
    entity_ids:
      - sensor.james_downstairs
      - sensor.james_upstairs
      
  - platform: min_max
    name: "Tina Home Occupancy Confidence"
    type: mean
    round_digits: 0
    entity_ids:
      - sensor.tina_downstairs
      - sensor.tina_upstairs

## Create Sensor for Display in UI      
  - platform: template
    sensors:
      james:
        friendly_name: "James Occupancy"
        value_template: >-
          {% if is_state('input_boolean.james_home', 'on') %}
            Home
          {% elif is_state('device_tracker.admin_samsung', 'Powertec') %}
            Powertec
          {% elif is_state('device_tracker.admin_samsung', 'Kindy') %}
            Kindy
          {% elif is_state('device_tracker.admin_samsung', 'Stocklands') %}
            Stocklands
          {% elif is_state('device_tracker.admin_samsung', 'Parlour') %}
            Parlour
          {% elif is_state('device_tracker.admin_samsung', 'Work Home Beacon 25mins') %}
            25mins Away
          {% elif is_state('device_tracker.admin_samsung', 'Work Home Beacon 15mins') %}
            15mins Away
          {% elif is_state('device_tracker.admin_samsung', 'Work Home Beacon 5mins') %}
            5mins Away
          {% else %}
            Away
          {% endif %}
        entity_picture_template: >-
          {% if is_state('input_boolean.james_home', 'on') %}
            /local/james.jpg
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.admin_samsung', 'Powertec') %}
            mdi:briefcase
          {% elif is_state('device_tracker.admin_samsung', 'Kindy') %}
            mdi:school
          {% elif is_state('device_tracker.admin_samsung', 'Stocklands') %}
            mdi:cart
          {% elif is_state('device_tracker.admin_samsung', 'Parlour') %}
            mdi:coffee
          {% elif is_state('device_tracker.admin_samsung', 'Work Home Beacon 25mins') %}
            mdi:car
          {% elif is_state('device_tracker.admin_samsung', 'Work Home Beacon 15mins') %}
            mdi:car
          {% elif is_state('device_tracker.admin_samsung', 'Work Home Beacon 5mins') %}
            mdi:car
          {% else %}
            mdi:walk
          {% endif %}
          
      tina:
        friendly_name: "Tina Occupancy"
        value_template: >-
          {% if is_state('input_boolean.tina_home', 'on') %}
            Home
          {% elif is_state('device_tracker.admin_iphone', 'Kindy') %}
            Kindy
          {% elif is_state('device_tracker.admin_iphone', 'Stocklands') %}
            Stocklands
          {% elif is_state('device_tracker.admin_iphone', 'Parlour') %}
            Parlour
          {% else %}
            Away
          {% endif %}
        entity_picture_template: >-
          {% if is_state('input_boolean.tina_home', 'on') %}
            /local/tina.jpg
          {% endif %}
        icon_template: >-
          {% if is_state('device_tracker.admin_iphone', 'Kindy') %}
            mdi:school
          {% elif is_state('device_tracker.admin_iphone', 'Stocklands') %}
            mdi:cart
          {% elif is_state('device_tracker.admin_iphone', 'Parlour') %}
            mdi:coffee
          {% else %}
            mdi:walk
          {% endif %}
    
## Google Travel Time
  - platform: google_travel_time
    api_key: !secret google_maps
    name: 'Commute to Work'
    origin: "your home address here"
    destination: "your work address here"
    
  - platform: google_travel_time
    api_key: !secret google_maps
    name: 'Commute to Home'
    origin: "Your work address here"
    destination: "Your home address here"
    
#################################################################
#                                                               #
#                         Automations                           #
#                                                               #
#################################################################

automation:

## Trigger Input Boolean James is Home
  - alias: James Occupancy Home 
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.james_home_occupancy_confidence
        above: 10
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.james_home
          
## Trigger Input Boolean James is Away
  - alias: James Occupancy Away
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.james_home_occupancy_confidence
        below: 10
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.james_home
          
  ## Trigger Input Boolean Tina is Home
  - alias: Tina Occupancy Home 
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.tina_home_occupancy_confidence
        above: 10
    action:
      - service: homeassistant.turn_on
        data:
          entity_id: input_boolean.tina_home
          
## Trigger Input Boolean Tina is Away
  - alias: Tina Occupancy Away
    hide_entity: true
    trigger:
      - platform: numeric_state
        entity_id: sensor.tina_home_occupancy_confidence
        below: 10
    action:
      - service: homeassistant.turn_off
        data:
          entity_id: input_boolean.tina_home
  
## Tina Home Announcement 
  - alias: Welcome Home Tina
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_iphone
      event: enter
      zone: zone.home
    action:
    - delay: 00:02:00
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "I have detected a disturbance in the force, oh welcome home Lord Tina."
        
## James Home Announcement
  - alias: Welcome Home James
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: enter
      zone: zone.home
    action:
    - delay: 00:01:00
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Welcome home James your arrival has caused a disturbance in the force."
        
## James at work announcement
  - alias: Dad at Work
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: enter
      zone: zone.powertec
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Daddy has arrived safely at work."
        
## James at 25mins from home announcement
  - alias: Work to Home 25min Notify
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: enter
      zone: zone.work_home_beacon_25mins
    condition:
    -  condition: time
       after: '13:00'
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Daddy is 25 minutes from home."
        
## James left work announcement
  - alias: Daddy Leaving Work Notify
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: leave
      zone: zone.powertec
    condition:
    -  condition: time
       after: '14:00'
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Daddy has left work and is on his way home, with normal traffic he should be 40 minutes."
        
## James at 15mins from home announcement
  - alias: Work to Home 15min Notify
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: enter
      zone: zone.work_home_beacon_15mins
    condition:
    -  condition: time
       after: '13:00'
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Daddy will be home in 15 minutes."
        
## James at 5mins from home announcement
  - alias: Work to Home 5min Notify
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: enter
      zone: zone.work_home_beacon_5mins
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "Warning Warning Warning, Daddy will be home in 5 minutes."
        
## James at shops announcement
  - alias: Alert Tina I'm at the Shops
    trigger:
    - platform: zone
      entity_id: device_tracker.admin_samsung
      event: enter
      zone: zone.stocklands
    action:
    - service: tts.google_say
      data:
        entity_id: media_player.tts_kodi
        message: "James is at the shops call him now if you need him pick up anything else"
        
