#################################################################
#                                                               #
#                      Packages/Weather                         #
#                                                               #
#################################################################

#################################################################
#                                                               #
#                          Customize                            #
#                                                               #
#################################################################

homeassistant:
  customize:

  
#################################################################
#                                                               #
#                           Group                               #
#                                                               #
#################################################################

group:
  sun:
    name: Sun
    view: no
    entities:
      - sun.sun
      - sensor.moon
      
  weather overview:
    name: Weather Overview
    view: no
    entities:
      - sensor.pws_temp_c
      - sensor.pws_relative_humidity
      - sensor.pws_precip_1d
      - sensor.pws_wind_kph
      - sensor.pws_alerts
      
  daily forcast:
    name: Daily Forcast
    view: no
    entities:
      - sensor.pws_temp_high_1d_c
      - sensor.pws_temp_high_2d_c
      - sensor.pws_temp_high_3d_c
      - sensor.pws_temp_high_4d_c
      
#################################################################
#                                                               #
#                            Sensors                            #
#                                                               #
#################################################################

sensor:
  - platform: moon
  
## Weather Dark Sky
  - platform: darksky
    api_key: 2395af4f72c2143ebe21cb8c4a8eb6e0
    forecast:
      - 1
      - 2
      - 3
      - 4
      - 5
    monitored_conditions:
      - icon
      - summary
      - nearest_storm_distance
      - nearest_storm_bearing
      - humidity
      - temperature
      - temperature_high
      - temperature_low
      - apparent_temperature
      - apparent_temperature_high
      - apparent_temperature_low
      - wind_speed
      - wind_bearing
      - precip_type
      - precip_probability
      - precip_accumulation
      - precip_intensity
      - precip_intensity_max
      - uv_index
      - daily_summary
      - pressure
      - visibility
    update_interval:
      minutes: 5
      
## Weather Sensors Weatherunderground
  - platform: wunderground
    api_key: !secret wunderground_api
    pwd_id: !secret wunderground_pws_id
    monitored_conditions:
      - relative_humidity
      - pressure_mb
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - precip_1d
      - precip_1d_mm
      - precip_today_string
      - wind_kph
      - wind_1d_kph
      - wind_dir
      - feelslike_c
      - alerts
      - temp_high_2d_c
      - temp_low_2d_c
      - temp_high_3d_c
      - temp_high_4d_c
      - weather_1d_metric
      - weather_2d_metric
      - weather_3d_metric
      - weather_4d_metric
      
## BOM Forecast
  - platform: bom_forecast
    product_id: IDQ10610
    name: GC Forecast
    forecast_days: 5
    rest_of_today: True
    friendly: False
    friendly_state_format: '{max}, {summary}'
    monitored_conditions:
      - 'max'
      - 'min'
      - 'chance_of_rain'
      - 'possible_rainfall'
      - 'summary'
      - 'detailed_summary'
     
  - platform: template
    sensors:
      bom_temp:
        friendly_name: "Gold Coast Temperature"
        value_template: "{{ states.weather.bom_gold_coast.attributes.temperature }}"
        device_class: temperature
        unit_of_measurement: °C
        
      bom_humd:
        friendly_name: "Gold Coast Humidity"
        value_template: "{{ states.weather.bom_gold_coast.attributes.humidity }}"
        #device_class: humidity
        unit_of_measurement: '%'
        
      bom_wind_sp:
        friendly_name: "Gold Coast Wind Speed"
        value_template: "{{ states.weather.bom_gold_coast.attributes.wind_speed }}"
        #device_class: temperature
        unit_of_measurement: km
        
      bom_wind_bear:
        friendly_name: "Gold Coast Wind Bearing"
        value_template: "{{ states.weather.bom_gold_coast.attributes.wind_bearing }}"
        #device_class: temperature
        #unit_of_measurement: km
        
      bom_pres:
        friendly_name: "Gold Coast Pressure"
        value_template: "{{ states.weather.bom_gold_coast.attributes.pressure }}"
        #device_class: temperature
        unit_of_measurement: hPa
        
####################################################
#                                                  #
#                     Weather                      #
#                                                  #
####################################################

sun:

weather:
  - platform: bom
    station: IDQ60801.94592
    name: Gold Coast
    monitored_conditions:
      - apparent_t
      - cloud
      - cloud_base_m
      - cloud_oktas
      - cloud_type_id
      - cloud_type
      - delta_t
      - gust_kmh
      - gust_kt
      - air_temp
      - dewpt
      - press
      - press_qnh
      - press_msl
      - press_tend
      - rain_trace
      - rel_hum
      - sea_state
      - swell_dir_worded
      - swell_height
      - swell_period
      - vis_km
      - weather
      - wind_dir
      - wind_spd_kmh
      - wind_spd_kt
  
